### PR TITLE
Fixed Issue #49 Redmine 3.0.3 higher

### PR DESCRIPTION
**Pull request by jp-yendo**
Redmine 3.0.3 higher.
Fixed an issue where the progress of the project is always 100%.

### CODE REVIEW

**Comment by stgeneral** [comment]
@jp-yendo thank you for the contribution. Did you took this code from the Redmine or this is your personal update?

**Comment by jp-yendo** [comment]
reference url
https://github.com/redmine/redmine/blob/master/app/models/issue_query.rb
When you study the mysql log "status" join not is of "where" even I was corrected for, which has not been specified.

**Comment by jp-yendo** [comment]
Details I've found.
This problem was caused by a version of ActiveRecord.
http://apidock.com/rails/ActiveRecord/Calculations/ClassMethods/sum

**Comment by Marqin** [comment]
Thanks, this is working for me :+1: 

@stgeneral, will You merge this pull request?

**Comment by stgeneral** [comment]
@jp-yendo thanks for the contribution!
@Marqin thank you for confirming the fix!

Fixes #58, #49, #46.

**Pull request merged**
